export const BadgeImages = { 
   "fairTradeBadge.png" : require('res/PNG/fairTradeBadge.png'),
   "directTradeBadge.png" : require('res/PNG/directTradeBadge.png'),
   "birdFriendlyBadge.png" : require('res/PNG/birdFriendlyBadge.png'),
   "organicBadge.png" : require('res/PNG/organicBadge.png'),
   "rainforestAllianceBadge.png" : require('res/PNG/rainforestAllianceBadge.png'),
   "shadeGrownBadge.png" : require('res/PNG/shadeGrownBadge.png'),
   "singleOriginBadge.png" : require('res/PNG/singleOriginBadge.png'),

   "fairTradeBadge-inv.png" : require('res/PNG/fairTradeBadge-inv.png'),
   "directTradeBadge-inv.png" : require('res/PNG/directTradeBadge-inv.png'),
   "birdFriendlyBadge-inv.png" : require('res/PNG/birdFriendlyBadge-inv.png'),
   "organicBadge-inv.png" : require('res/PNG/organicBadge-inv.png'),
   "rainforestAllianceBadge-inv.png" : require('res/PNG/rainforestAllianceBadge-inv.png'),
   "shadeGrownBadge-inv.png" : require('res/PNG/shadeGrownBadge-inv.png'),
   "singleOriginBadge-inv.png" : require('res/PNG/singleOriginBadge-inv.png'),

   "AbesCafe" : require('res/avatars/AbesCafe.jpg'),
   "AlgorithmCoffeeCo" : require('res/avatars/AlgorithmCoffeeCo.jpg'),
   "BabetteBampfa" : require('res/avatars/BabetteBampfa.jpg'),
   "BabetteSouthHall" : require('res/avatars/BabetteSouthHall.jpg'),
   "BrewedAwakening" : require('res/avatars/BrewedAwakening.jpg'),
   "GoldLeafCafe" : require('res/avatars/GoldLeafCafe.jpg'),
   "NorthsideCafe" : require('res/avatars/NorthsideCafe.jpg'),
   "PeoplesCafe" : require('res/avatars/PeoplesCafe.jpg'),
   "VictoryPointCafe" : require('res/avatars/VictoryPointCafe.jpg'),
   "BearMarket" : require('res/avatars/CalDining.jpg'),
   "Cafe3" : require('res/avatars/CalDining.jpg'),
   "CKCDining" : require('res/avatars/CalDining.jpg'),
   "CKCub" : require('res/avatars/CalDining.jpg'),
   "CoffeeCartRSF" : require('res/avatars/CalDining.jpg'),
   "CommonGrounds" : require('res/avatars/CalDining.jpg'),
   "Crossroads" : require('res/avatars/CalDining.jpg'),
   "Foothill" : require('res/avatars/CalDining.jpg'),
   "FoothillCubMarket" : require('res/avatars/CalDining.jpg'),
   "GoldenBearCafe" : require('res/avatars/CalDining.jpg'),
   "HaasPavilion" : require('res/avatars/CalDining.jpg'),
   "MemorialStadium" : require('res/avatars/CalDining.jpg'),
   "PatBrowns" : require('res/avatars/CalDining.jpg'),
   "TerraceCafe" : require('res/avatars/CalDining.jpg'),
   "TheDen" : require('res/avatars/CalDining.jpg'),
   "TheProShop" : require('res/avatars/CalDining.jpg'),
   "BearMarket" : require('res/avatars/CalDining.jpg'),
}